#!/sbin/sh

if [ -e /cache/recovery/boot ]
then

rm /cache/recovery/boot
touch /cache/recovery/enterrecovery

else

# trigger blue LED
echo '255' > /sys/class/leds/l-key-red/brightness
echo '255' > /sys/class/leds/m-key-green/brightness
echo '255' > /sys/class/leds/r-key-blue/brightness
# trigger vibration
echo '200' > /sys/class/timed_output/vibrator/enable
# trigger button-backlight
echo '255' > /sys/class/leds/button-backlight/brightness
cat /dev/input/event2 > /dev/keycheck&
sleep 3

# trigger blue LED
echo '0' > /sys/class/leds/l-key-red/brightness
echo '0' > /sys/class/leds/m-key-green/brightness
echo '0' > /sys/class/leds/r-key-blue/brightness
# trigger button-backlight
echo '0' > /sys/class/leds/button-backlight/brightness

kill -9 $!

fi


if [ -s /dev/keycheck -o -e /cache/recovery/enterrecovery ]
then

rm /cache/recovery/enterrecovery


mount -o remount,rw rootfs /
# shifting to "umount -l /partition" to avoid mounting issues in recovery
umount -l /system
umount -l /data
umount -l /cache
umount -l /sdcard
umount -l /mnt/sdcard
rm -r /sdcard
rm -r /not/sdcard
mkdir /sdcard
mkdir /tmp
rm /etc
mkdir /etc
cp /recovery.fstab /etc/recovery.fstab
mount /dev/block/mmcblk0p14 /sdcard

# DooMLoRD - enable USB Mass Storage mode - thanks to Napstar
echo 1 > /sys/devices/virtual/usb_composite/usb_mass_storage/enable

/sbin/recovery &
/sbin/adbd_rec recovery 
fi

#continue booting
/system/bin/chargemon
